name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # Job for linting, testing, and building Android app
  android:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js (Android)
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Yarn globally (Android)
        run: |
          npm install -g yarn

      - name: Install Android SDK and dependencies (Android)
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk
          sudo apt-get install -y android-sdk
          sudo apt-get install -y gradle
          yarn install

      - name: Set up React Native environment variables (Android)
        run: |
          echo "export ANDROID_HOME=/usr/lib/android-sdk" >> $GITHUB_ENV
          echo "export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools" >> $GITHUB_ENV

      - name: Run Android lint
        run: yarn run lint

      - name: Run Android tests
        run: yarn test

      - name: Build Android app
        run: yarn android

  # Job for linting, testing, and building iOS app
  ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js (iOS)
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Yarn globally (iOS)
        run: |
          npm install -g yarn

      - name: Install dependencies (iOS)
        run: |
          brew install cocoapods
          yarn install 
          cd ios && pod install && cd ..

      - name: Run iOS lint
        run: yarn run lint

      - name: Run iOS tests
        run: yarn test

      - name: Build iOS app
        run: yarn ios
